homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret coord_latitude
  longitude: !secret coord_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret coord_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret coord_timezone
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret api_password
  #ssl_certificate: /config/certificate.pem
  #ssl_key: /config/privkey.pem  
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  #base_url: https://192.168.2.100:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

#ios
ios:

#device trackers
device_tracker:
  - platform: ddwrt
    host: !secret router_address
    username: !secret router_login
    password: !secret router_pwd
    track_new_devices: no

#enable logging
logger:
  default: info

#mqtt broker
mqtt:
  broker: !secret mqttserver
  port: !secret mqttport
#  username: !secret mqttusername
#  password: !secret mqttpassword

#python scripting
python_script:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

#notifications
notify:
  - name: jasonprowl 
    platform: prowl
    api_key: !secret jason_prowl_api
  - name: beckyprowl
    platform: prowl
    api_key: !secret becky_prowl_api
    
#history graph
#history_graph:
#  gr1:
#    name:
#    entities:
#    hours_to_show:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

#Apple TV
apple_tv:
  - host: 192.168.2.103
    login_id: !secret apple_tv_lr_login
    name: Living Room Apple TV
    start_off: true
    credentials: !secret apple_tv_lr_cred

#Ring Doorbell
ring:
    username: !secret ring_login
    password: !secret ring_password
    
#ecobee
ecobee:
  api_key: !secret ecobee_api
  
#alarm control panel
alarm_control_panel:
  - platform: totalconnect
    username: !secret totalconnect_user
    password: !secret totalconnect_password

binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

sensor:
  - platform: ring
    monitored_conditions:
      - battery
      - last_activity
      - last_ding
      - last_motion
      - volume  
  - platform: wunderground
    api_key: !secret wunderground_api
    monitored_conditions:
      - alerts
      - temp_f
      - feelslike_f
      - temp_high_1d_f
      - temp_low_1d_f
      - weather_1d
      - precip_1d
      - weather_1n
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Back Door"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 570765) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 570765) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Garage Door"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 968216) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 968216) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Front Door"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 528831) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 528831) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Living Room Window 1"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 455187) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 455187) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Living Room Window 2"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 655210) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 655210) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Living Room Window 3"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 443393) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 443393) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Kitchen Window"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 818030) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 818030) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Kitchen Window 2"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 402860) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 402860) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Dining Room Window"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 364980) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 364980) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Dining Room Window 2"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 935692) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 935692) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
  - platform: mqtt
    state_topic: "homeassistant/sensor/honeywell"
    name: "Office Window"
    qos: 0
    device_class: opening
    value_template: '{% if (value_json.id is equalto 282194) and (value_json.event is equalto 160) %} open {% elif (value_json.id is equalto 282194) and (value_json.event is equalto 128) %} closed {% else %} {{states.sensor.kitchen_window.state}} {% endif %}'
input_boolean:
  nr_movietime:
    name: Movie Time workflow
    initial: false
  nr_nighttime:
    name: Night Time workflow
    initial: false
  nr_alldownstairs100:
    name: Downstairs lights at 100% workflow
    initial: false
  nr_alldownstairs75:
    name: Downstairs lights at 75% workflow
    initial: false
  nr_alldownstairs50:
    name: Downstairs lights at 50% workflow
    initial: false
  nr_alldownstairs25:
    name: Downstairs lights at 25% workflow
    initial: false    

# Zwave control
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  polling_interval: 10000
  device_config:
    #master bedroom overhead
    light.master_bedroom_level:
      polling_intensity: 1      
    #master bathroom vanity
    light.master_bathroom_level:
      polling_intensity: 1   
    #living room overhead downlights      
    light.living_room_1_level:
      polling_intensity: 1    
    #living room overhead downlights wet bar      
    light.living_room_2_level:
      polling_intensity: 1          
    #dining room overhead  
    light.dining_room_level:      
      polling_intensity: 1  
    #downstairs hallway
    light.downstairs_hallway_level:      
      polling_intensity: 1   
    #living room overhead fan
    switch.living_room_fan_switch:
      polling_intensity: 1    
    #kitchen eat in
    switch.eat_in_switch:
      polling_intensity: 1  
    #kitchen overhead flourescent      
    switch.kitchen_switch:  
      polling_intensity: 1    
    #entryway overhead      
    switch.entryway_switch:
      polling_intensity: 1  
    #outside porch lights
    switch.front_porch_switch:      
      polling_intensity: 1
    #mudroom switch
    switch.mudroom_switch:
      polling_intensity: 1
    #wemo mini plug
    switch.christmas_accent:
      polling_intensity: 1
    #wemo mini plug
    switch.christmas_tree:
      polling_intensity: 1
    #wemo full sized
    switch.my_lamp:
      polling_intensity: 1

         
scene:
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
